-- Your SQL goes here
CREATE TABLE `user`(
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`picture` VARCHAR(255) NOT NULL,
	`sub` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

