[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.41", features = ['serde']} 
diesel = {version =  "2.2.10", features = ["mysql", "r2d2" , "chrono"]}
dotenv = "0.15.0"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
